# Generated by Django 5.1.2 on 2024-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WebApplication', 'Web Application'), ('MoblieApplication', 'Moblie Application'), ('SciencePaper', 'Science Paper')], max_length=256),
        ),
    ]
