# Generated by Django 5.1.2 on 2024-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('Front End', 'Front End'), ('Back End', 'Back End'), ('Tool', 'Tool')], max_length=256)),
            ],
        ),
    ]
